server:
  port: 8084

spring:
  application:
    name: consumer-fegin
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8086
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka,http://peer3:8763/eureka

feign:
  hystrix:
    enabled: true